engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/FormatParameterMismatch: { enabled: false } # Because it badly detects "%c" % 27
      Rubocop/Lint/UselessAccessModifier:   { enabled: false } # Because this is a useless check, we are explicit.
      Rubocop/Lint/AssignmentInCondition:   { enabled: false } # Because we often do !(var = val)

  fixme:
    enabled: true
    exclude_fingerprints:
    - e6a45a3fb622ca145faa2141e4d641a9 # Because apparently RoboCop doesn't know what useless is.
    - e00463ba87b84ce062802709fc774669 # It badly detects "report a bug" as a "BUG" flag.
    - c42b72af850c2590419dfa0bb4d15004 # Because CodeClimate adds .rubocop.yml
    - b86af833d6b2b1fa18da63471e2278d9 # Because CodeClimate adds .rubocop.yml
    - ee0a31701f95b21db4aff40647a56a3d # Because CodeClimate adds .rubocop.yml
    - cdc1cac1f5cb7afe72dca9f9bca8a237 # Because CodeClimate adds .rubocop.yml
exclude_paths: [test/**/*, script/**/*]
ratings: [lib/**/*]
