Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/StringLiterals: { EnforcedStyle: double_quotes }

Style/HashSyntax:
  UseHashRocketsWithSymbolValues: false
  SupportedStyles: [ruby19 ruby19_no_mixed_keys, hash_rockets]
  EnforcedStyle: ruby19
