---
cache: bundler
os:
- linux
- osx
rvm:
- 2.0
- 2.1
- 2.2
- jruby-9.0.3.0
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-9.0.3.0
  - os: osx
  exclude:
  - rvm: 2.1
    os: osx
  - rvm: 2.2
    os: osx
  - rvm: ruby-head
    os: osx
  - rvm: jruby-9.0.3.0
    os: osx
notifications:
  email:
  - jordon@envygeeks.io
branches:
  only:
  - master
